aspc/sagelist/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from aspc.sagelist.views import (CreateBookSaleView, BookSaleDetailView,
    ListBookSalesView, ListCourseBookSalesView, ListUserBookSalesView, BookSaleDeleteView, create_many)

urlpatterns = [
    url(r'^$', ListBookSalesView.as_view(), name="sagelist"),
    url(r'^create/$', login_required(CreateBookSaleView.as_view()), name="sagelist_create"),
    url(r'^create_many/$', create_many, name="sagelist_create_many"),
    url(r'^(?P<pk>\d+)/$', BookSaleDetailView.as_view(), name="sagelist_detail"),
    url(r'^(?P<pk>\d+)/delete/$', BookSaleDeleteView.as_view(), name="sagelist_delete"),
    url(r'^course/(?P<course_id>\d+)/', ListCourseBookSalesView.as_view(), name="sagelist_course_listings"),
    url(r'^(?P<email>[^/]+)/$', ListUserBookSalesView.as_view(), name="sagelist_user_listings"),
]

aspc/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from aspc.folio.models import Page
from aspc.views import HomeView
from aspc.blog.urls import post_kwargs
from django.http import HttpResponseRedirect
from django.contrib import admin
import debug_toolbar

# home_kwargs = post_kwargs.copy()
# home_kwargs.update({'template_name': 'home.html'})

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('aspc.api.urls')),
    url(r'^news/', include('aspc.blog.urls')),
    url(r'^eatshop/', include('aspc.eatshop.urls')),
    url(r'^events/', include('aspc.events.urls')),
    url(r'^senate/meetings-and-minutes/', include('aspc.minutes.urls')),
    url(r'^senate/', include('aspc.senate.urls')),
    url(r'^sagebooks/', include('aspc.sagelist.urls')),
    url(r'^accounts/', include('aspc.auth2.urls')),
    url(r'^housing/', include('aspc.housing.urls')),
    url(r'^courses/', include('aspc.courses.urls')),
    url(r'^menu/', include('aspc.menu.urls')),
    url(r'^mentalhealth/', include('aspc.mentalhealth.urls')),
    url(r'^forum/', include('aspc.forum.urls')),
    url(r'^rideshare/', lambda request: HttpResponseRedirect('http://5crideshare.com')),
    url(r'^course-reviews/', lambda request: HttpResponseRedirect('/courses/reviews/')),
    url(r'(?P<slug_path>(?:[\w\-\d]+/)+)$', 'aspc.folio.views.page_view', name="folio_page"),
    url(r'^__debug__/', include(debug_toolbar.urls)),
]


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
            }),
    )

aspc/sagelist/models.py
from django.db import models
from django.contrib.auth.models import User
from aspc.activityfeed.signals import new_activity, delete_activity
from aspc.courses.models import Course
from amazon.api import AmazonAPI
import datetime
from aspc.settings import AMAZON_ACCESS_KEY, AMAZON_SECRET_KEY, AMAZON_ASSOC_TAG
import json
import logging

logger = logging.getLogger(__name__)
amazon = AmazonAPI(AMAZON_ACCESS_KEY, AMAZON_SECRET_KEY, AMAZON_ASSOC_TAG)

class BookSale(models.Model):
    CONDITIONS = (
        (0, "like new"),
        (1, "very good"),
        (2, "good"),
        (3, "usable"),
    )

    # See http://www.pomona.edu/administration/sustainability/programs/recoop.aspx
    # Record these so ReCoop listings can be disabled on these days
    RECOOP_SALE_DATES = [
        datetime.date(2014, 8, 31),
        datetime.date(2014, 9, 1),
        datetime.date(2014, 9, 2),
        datetime.date(2014, 9, 3),
        datetime.date(2014, 9, 4)
    ]

    """Model representing a sale of a textbook"""
    title = models.CharField(max_length=255)
    authors = models.CharField(max_length=255, verbose_name="Author(s)", null=True, blank=True)
    course = models.ForeignKey(Course, blank=True, null=True)
    isbn = models.CharField(max_length=20, verbose_name="ISBN")
    edition = models.CharField(max_length=30, null=True, blank=True)
    condition = models.IntegerField(choices=CONDITIONS)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    copies = models.IntegerField(default=1)
    is_recoop = models.BooleanField(default=False)
    recoop_id = models.IntegerField(unique=True, null=True)

    seller = models.ForeignKey(User, related_name="book_sales_set")
    buyer = models.ForeignKey(User, null=True, blank=True, related_name="book_purchases_set")

    posted = models.DateTimeField(auto_now_add=True)

    amazon_info = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['posted']

    def __unicode__(self):
        return u"BookSale: {0} by {1} ({2})".format(self.title, self.authors, self.seller.username)

    def save(self, *args, **kwargs):
        created = self.pk is None
        super(BookSale, self).save(*args, **kwargs)
        if created and not self.is_recoop:
            new_activity.send(sender=self, category="sagelist", date=self.posted)

    def update_amazon_info(self):
        if not self.isbn:
            return
        try:
            products = amazon.search_n(1,Keywords=self.isbn.replace('-',''), SearchIndex='Books')
        except:
            logger.error(e)
            return
        amazon_info = {}
        amazon_info['price'] = products[0].price_and_currency[0]
        amazon_info['image_url'] = products[0].large_image_url
        amazon_info['url'] = products[0].offer_url
        amazon_info['description'] = products[0].editorial_review
        self.title = products[0].title
        self.authors = products[0].author
        if products[0].edition is not None and products[0].edition.isdigit():
                self.edition = products[0].edition
        self.amazon_info = json.dumps(amazon_info)
        self.save()

    def get_amazon_attribute(self, attribute):
        if not self.amazon_info:
            return None
        amazon_info = json.loads(self.amazon_info)
        return amazon_info.get(attribute)

    def amazon_price(self):
        return self.get_amazon_attribute('price')

    def url(self):
        return self.get_amazon_attribute('url')

    def image_url(self):
        return self.get_amazon_attribute('image_url')

    def description(self):
        return self.get_amazon_attribute('description')

    def money_saved(self):
        if not self.amazon_price() or self.price > self.amazon_price():
            return 0
        return self.amazon_price() - float(self.price)

    def delete(self, *args, **kwargs):
        delete_activity.send(sender=self)
        super(BookSale, self).delete(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('sagelist_detail', [self.id])

    @property
    def is_frozen(self):
        return self.is_recoop and datetime.date.today() in self.RECOOP_SALE_DATES

aspc/sagelist/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseForbidden, HttpResponseRedirect, HttpResponse
from django.db.models import Q
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView
from django import forms
from django.template.loader import render_to_string
from django.template import RequestContext
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404, render, redirect
from aspc.sagelist.models import BookSale
from aspc.courses.models import Course
import string
import re
import logging
import time

logger = logging.getLogger(__name__)

class BookSaleForm(forms.ModelForm):
    class Meta:
        model = BookSale
        exclude = ('buyer', 'seller', 'posted', 'is_recoop', 'recoop_id', 'amazon_info')

class BookSearchForm(forms.Form):
    search = forms.CharField(initial="search")

class CreateBookSaleView(CreateView):
    form_class = BookSaleForm
    model = BookSale

    def form_valid(self, form):
        sale = form.save(commit=False)
        sale.title = sale.title.strip()
        sale.isbn = re.sub("[^0-9X]", "", sale.isbn)
        sale.authors = sale.authors.strip()
        sale.seller = self.request.user
        sale.save()
        try:
            sale.update_amazon_info()
        except Exception as e:
            logger.error(e)
        sale.seller.email_user(
            u"Posted {0} on SageBooks".format(sale.title),
            render_to_string(
                'sagelist/new_listing.txt',
                {'seller': sale.seller, 'booksale': sale,},
                context_instance=RequestContext(self.request)
            )
        )
        messages.add_message(self.request, messages.SUCCESS, u"Successfully listed {0} for sale".format(sale.title))
        return super(CreateBookSaleView, self).form_valid(form)


class BookSaleDetailView(DetailView):
    model = BookSale
    context_object_name = "book"

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.seller == request.user:
            return HttpResponseRedirect(reverse('sagelist_detail', kwargs={'pk': self.object.pk,}))
        self.object = self.get_object()
        self.object.buyer = request.user

        email_context = {
            'seller': self.object.seller,
            'buyer': self.object.buyer,
            'booksale': self.object,
        }

        if self.object.is_recoop:
            buyer_email_template = 'sagelist/recoop_purchase_complete_buyer.txt'
            seller_email_template = 'sagelist/recoop_purchase_complete_seller.txt'
        else:
            buyer_email_template = 'sagelist/purchase_complete_buyer.txt'
            seller_email_template = 'sagelist/purchase_complete_seller.txt'

        self.object.buyer.email_user(
            u"Purchase of {0} from {1}".format(
                self.object.title,
                self.object.seller.get_full_name()
            ),
            render_to_string(
                buyer_email_template,
                email_context,
                context_instance=RequestContext(self.request)
            )
        )

        self.object.seller.email_user(
            u"Sale of {0} to {1}".format(
                self.object.title,
                self.object.buyer.get_full_name()
            ),
            render_to_string(
                seller_email_template,
                email_context,
                context_instance=RequestContext(self.request)
            )
        )

        self.object.save()
        messages.add_message(self.request, messages.SUCCESS, u"Purchased {0}. An email has been sent to you and the seller.".format(self.object.title))
        return self.get(request, *args, **kwargs)

class BookSaleDeleteView(DeleteView):
    model = BookSale
    context_object_name = "book"

    class AccessDenied(Exception):
        pass

    def get_success_url(self):
        return reverse('sagelist')

    def user_can_delete(self):
        return (self.get_object().seller == self.request.user or
                self.request.user.has_perm('sagelist.delete_booksale'))

    def dispatch(self, *args, **kwargs):
        try:
            return super(BookSaleDeleteView, self).dispatch(*args, **kwargs)
        except BookSaleDeleteView.AccessDenied:
            return HttpResponseForbidden("Only the seller or an administrator may delete this listing")

    def get_object(self):
        obj = super(BookSaleDeleteView, self).get_object()
        if not (obj.seller == self.request.user or
                self.request.user.has_perm('sagelist.delete_booksale')):
            raise BookSaleDeleteView.AccessDenied
        return obj

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.copies > 1:
            self.object.copies -= 1
            self.object.save()
            messages.add_message(request, messages.SUCCESS, u"Decremented listing for {0}".format(self.object.title))
        else:
            self.object.delete()
            messages.add_message(request, messages.SUCCESS, u"Deleted listing for {0}".format(self.object.title))
        return HttpResponseRedirect(self.get_success_url())


class ListUserBookSalesView(ListView):
    model = BookSale
    context_object_name = "listings"
    template_name = "sagelist/booksale_list_user.html"
    _user = None

    def get_context_data(self, *args, **kwargs):
        context = super(ListUserBookSalesView, self).get_context_data(*args, **kwargs)
        context.update({
            'listings_by': self._get_user(),
        })
        return context

    def _get_user(self):
        if not self._user:
            self._user = get_object_or_404(User, email__iexact=self.kwargs['email'])
        return self._user

    def get_queryset(self):
        qs = super(ListUserBookSalesView, self).get_queryset()
        qs = qs.filter(seller=self._get_user())
        return qs

class ListCourseBookSalesView(ListView):
    model = BookSale
    context_object_name = "listings"
    template_name = "sagelist/booksale_list_course.html"
    _course = None

    def get(self, request, *args, **kwargs):
        self._course = get_object_or_404(Course, pk=self.kwargs['course_id'])
        return super(ListCourseBookSalesView, self).get(self, request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(ListCourseBookSalesView, self).get_context_data(*args, **kwargs)
        context.update({
            'course': self._course,
        })
        return context

    def get_queryset(self):
        qs = super(ListCourseBookSalesView, self).get_queryset()
        qs = qs.filter(course=self._course, buyer__isnull=True).order_by('title')
        return qs

class ListBookSalesView(ListView):
    model = BookSale
    context_object_name = "listings"
    paginate_by = 100

    def get_queryset(self):
        form = BookSearchForm(self.request.GET)

        qs = super(ListBookSalesView, self).get_queryset()
        qs = qs.filter(buyer__isnull=True).order_by('title')

        if form.is_valid():
            query = Q(title__icontains=form.cleaned_data['search'])
            query |= Q(authors__icontains=form.cleaned_data['search'])
            query |= Q(edition__icontains=form.cleaned_data['search'])
            query |= Q(isbn__icontains=form.cleaned_data['search'])
            qs = qs.filter(query)

        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(ListBookSalesView, self).get_context_data(*args, **kwargs)

        form = BookSearchForm(self.request.GET)
        if form.is_valid:
            context['form'] = form
            context['search'] = True
        else:
            context['form'] = BookSearchForm()
            context['search'] = False

        context['total_for_sale'] = self.model.objects.filter(buyer__isnull=True).count()
        context['total_sold'] = self.model.objects.filter(buyer__isnull=False).count()
        context['total'] = self.model.objects.count()
        return context

def create_many(request):
    if request.user.username != 'sustainability@pomona.edu':
        return redirect(reverse('sagelist'))
    if request.method == 'GET':
        return render(request,"sagelist/booksale_many_form.html")
    text = request.POST['text']
    parse_csv(text)
    return redirect(reverse('sagelist'))

def parse_csv(text):
    lines = text.split('\r\n')
    for line in lines:
        parts = line.split(',')
        if len(parts) != 3:
            continue
        for i in range(0,3):
            if parts[i][0] == '<' and parts[i][-1] == '>' and len(parts[i]) > 2:
                parts[i] = parts[i][1:-1]
        sale = BookSale(isbn=parts[0], is_recoop=True, condition=2,
                        seller=User.objects.get(username='sustainability@pomona.edu'),
                        copies=parts[1], price=parts[2],  title='', authors='')
        try:
            sale.update_amazon_info()
        except:
            continue
        sale.save()
        time.sleep(0.5)

aspc/sagelist/templates/sagelist/base.html
{% extends "base_page.html" %}

{% load staticfiles %}

{% block "page_class" %}sagelist{% endblock %}
{% block "title" %}SageBooks {% block "subtitle" %}{% endblock %}{% endblock %}
{% block "page_title" %}SageBooks Textbook Sales{% endblock %}

{% block "css" %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "css/sagelist/sagelist.css" %}"/>
{% endblock %}

{% block "mobile_css" %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "css/sagelist/sagelist.mobile.css" %}"/>
{% endblock %}

{% block "breadcrumbs" %}
<ol class="breadcrumbs">
  <li><a href="{% url "sagelist" %}">SageBooks</a></li>
  {% block "sagelist_breadcrumbs" %}
  {% endblock %}
</ol>
{% endblock %}

aspc/sagelist/templates/sagelist/booksale_confirm_delete.html
{% extends "sagelist/booksale_detail.html" %}
{% block "form" %}
{% include "sagelist/booksale_delete_form.html" %}
{% endblock %}

aspc/sagelist/templates/sagelist/booksale_delete_form.html
<p>Nobody has purchased this book yet. You can still remove this listing if you want.</p>
<form action="{% url "sagelist_delete" pk=book.id %}" method="POST">
  {% csrf_token %}
  <p><input type="submit" value="Delete this listing" id="delete"></p>
</form>

aspc/sagelist/templates/sagelist/booksale_detail.html
{% extends "sagelist/base.html" %}
{% block "subtitle" %}&mdash; {{ book.title }}{% block "subsubtitle" %}{% endblock %}{% endblock %}
{% block "page_title" %}{{ book.title }}{% endblock %}
{% block "sagelist_breadcrumbs" %}
    {% load static %}
  <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
{% endblock %}
{% block "content" %}
<dl class="detail half-width">
  <dt>Title</dt>
  <dd>{{ book.title }}</dd>
  <dt>Author(s)</dt>
  <dd>{{ book.authors }}</dd>
  {% if book.edition %}<dt>Edition</dt>
  <dd>{{ book.edition }}</dd>
  {% endif %}
  <dt>Copies</dt>
  <dd>{{ book.copies }}</dd>
  {% if book.isbn %}<dt>ISBN</dt>
  <dd>{{ book.isbn }}</dd>
  {% endif %}
  {% if book.course %}<dt>Course</dt>
  <dd>{{ book.course.name }}</dd>
  {% endif %}
  <dt>Condition</dt>
  <dd>{{ book.get_condition_display }}</dd>
  <dt>Price</dt>
  <dd>${{ book.price }}
  {% if book.money_saved %}
      <small><a href="{{ book.url }}">${{ book.money_saved|floatformat:2  }} cheaper than a new version on Amazon!</a></small>
  {% endif %}</dd>
  <dt>Posted by</dt>
  <dd>{{ book.seller.get_full_name }} on {{ book.posted }}</dd>
  {% if book.buyer %}
  <dt>Purchased by</dt>
  <dd>{{ book.buyer.get_full_name }}</dd>
  {% endif %}
</dl>
    <div class='book_image_div'>
    {% if book.image_url %}
        <img class='book_image' src="{{ book.image_url }}">
    {% else %}
        <img class='book_image' src="{% static 'images/no_image.png' %}">
    {% endif %}
    </div>
{% if book.description %}
    <dl class="detail">
      <dt>Description</dt>
      <dd>{{ book.description|safe }}</dd>
    </dl>
{% endif %}
{% if book.is_recoop %}
  <dt class="detail_note">Note</dt>
  <dd class="detail_note"><i>This is a ReCoop listing through the Sustainability Office! You can purchase the book like normal here on SageBooks, and then pick it up at the Walker EcoDesk in Walker Lounge. For Spring 2016, the book room will be open Monday (January 25) through Thursday (January 25), 7 to 9pm. Contact <a href="mailto:sustainability@pomona.edu">sustainability@pomona.edu</a> with questions.</i></dd>
{% endif %}
<div class="info">
{% block "form" %}
{% if book.is_recoop and book.is_frozen %}
<p>
  <strong>Attention:</strong> Today is the day of the ReCoop sale! Head over to Walker Lounge to buy this book in person; you can't reserve it online right now.
</p>
{% elif not book.buyer and not book.seller == user %}
  <p>
    <strong>Attention:</strong> By clicking "buy this book" you are agreeing to make a purchase. Your
    name and email will be sent to the seller, and you will receive an email
    with their contact info.
  </p>
  <form action="." method="POST">
    {% csrf_token %}
    <p><input type="submit" value="Buy this book" id="buy"></p>
  </form>
{% endif %}
{% if book.seller == user and not book.buyer %}
{% include "sagelist/booksale_delete_form.html" %}
{% endif %}
{% endblock %}
</div>
{% endblock %}

aspc/sagelist/templates/sagelist/booksale_form.html
{% extends "sagelist/base.html" %}
{% block "subtitle" %}&mdash; Sell a Book{% endblock %}
{% block "page_title" %}Sell a Book{% endblock %}
{% block "sagelist_breadcrumbs" %}
  <li>Sell a Book</li>
{% endblock %}
{% block "content" %}
<form action="." method="POST">
  {% csrf_token %}
  <ul>
    <li><span class="faux_label">Seller:</span> {{ user.get_full_name }}</li>
    {{ form.non_field_errors }}
    <li>{{ form.title.errors }}<label for="id_title">Title:</label> {{ form.title }}</li>
    <li>{{ form.authors.errors }}<label for="id_authors">Author(s):</label> {{ form.authors }}</li>
    <li>{{ form.isbn.errors }}<label for="id_isbn">ISBN:</label> {{ form.isbn }}</li>
    <li>{{ form.edition.errors }}<label for="id_edition">Edition <span class="optional">(optional)</span>:</label> {{ form.edition }} (e.g. "1st", "2nd", "International")</li>
    <li>{{ form.condition.errors }}<label for="id_condition">Condition:</label> {{ form.condition }}</li>
    <li>{{ form.course.errors }}<label for="id_course">Course:</label> {{ form.course }}</li>
    <li>{{ form.price.errors }}<label for="id_price">Price:</label> ${{ form.price }}</li>
    <li>{{ form.copies.errors }}<label for="id_price">Copies:</label> {{ form.copies }}</li>
  </ul>
  <p><strong>Note:</strong> by listing your book on SageBooks, you are agreeing
    to sell it to the person who clicks "buy" on your listing page. If you sell
    the book outside SageBooks, you must come back and delete your listing!</p>
  <p><input type="submit" value="Post new listing" id="post"></p>
</form>
{% endblock %}

aspc/sagelist/templates/sagelist/booksale_list.html
{% extends "sagelist/base.html" %}

{% load staticfiles %}

{% block "breadcrumbs" %}{% endblock %}
{% block "outer_content" %}
<ul class="actions">
  <li><a href="{% url "sagelist_create" %}">List a book for sale</a></li>
  <li><a href="{% url "sagelist_create_many" %}">List many books for sale</a></li>
  {% if user.is_authenticated %}
  <li><a href="{% url "sagelist_user_listings" email=user.email %}">View my listings</a></li>
  {% endif %}
</ul>

<div class="stat_search">
  <ul class="stats">
    {% if total_for_sale %}<li>{{ total_for_sale }} book{% if total_for_sale != 1 %}s{% endif %} for sale</li>{% endif %}
    {% if total_sold %}<li>{{ total_sold }} book{% if total_sold != 1 %}s{% endif %} sold</li>{% endif %}
  </ul>
  <form action="." method="GET" id="search_form">
    {% if search %}
      <a href=".">clear</a>
    {% endif %}
      {{ form.search }}
    <input type="submit" value="search">
  </form>

</div>

{% if listings %}
  {% include "includes/pagination.html" %}

    {% include 'sagelist/booksale_table.html' %}

  {% include "includes/pagination.html" %}

{% else %}
  <p class="list_empty content">{% if not search %}No books are currently listed for sale.{% else %}No book listings matched your search. <a href="{% url "sagelist_create" %}">Post a new one?</a>{% endif %}</p>
{% endif %}

{% endblock %}

aspc/sagelist/templates/sagelist/booksale_list_course.html
{% extends "sagelist/base.html" %}
{% block "full_content" %}
<ol class="breadcrumbs">
  <li><a href="{% url "sagelist" %}">SageBooks</a></li>
  <li>Listings for {{ course.code }}</li>
</ol>
<h1>Listings for {{ course.name }}</h1>
<ul class="actions">
  <li><a href="{% url "sagelist_create" %}">List a book for sale</a></li>
</ul>
{% if listings %}
{% include 'sagelist/booksale_table.html' %}
{% else %}
<p class="list_empty content">This course doesn't have any books for sale yet. <a href="{% url "sagelist_create" %}">Post a new one?</a></p>
{% endif %}
{% endblock %}

aspc/sagelist/templates/sagelist/booksale_list_user.html
{% extends "sagelist/base.html" %}
{% block "full_content" %}
<ol class="breadcrumbs">
  <li><a href="{% url "sagelist" %}">SageBooks</a></li>
  <li>Listings by {{ listings_by.get_full_name }}</li>
</ol>
<h1>Listings by {{ listings_by.get_full_name }}</h1>
<ul class="actions">
  <li><a href="{% url "sagelist_create" %}">List a book for sale</a></li>
</ul>
{% if listings %}
    {% include 'sagelist/booksale_table.html' %}
{% else %}
<p class="list_empty content">You haven't listed any books for sale yet. <a href="{% url "sagelist_create" %}">Post a new one?</a></p>
{% endif %}
{% endblock %}

aspc/sagelist/templates/sagelist/booksale_many_form.html
{% extends "sagelist/base.html" %}
{% block "subtitle" %}&mdash; Sell Books{% endblock %}
{% block "page_title" %}Sell Books{% endblock %}
{% block "sagelist_breadcrumbs" %}
  <li>Sell Books</li>
{% endblock %}
{% block "content" %}
<form action="." method="POST">
  {% csrf_token %}
  <p><strong>Note:</strong> This is supposed to be used only by ReCoop. Copy the text in your csv file into the textbox
  below. If there many listings, you may get a timeout error. Check your new listings after the upload. If any listing
  have empty titles and authors. Delete it and create the listing manually. Thank you.</p>
  <textarea required="required" rows="20" cols="140" placeholder="Format: <ISBN>,<number of copies>,<price>" name="text"></textarea>
  <p><input type="submit" value="Post new listing" id="post"></p>
</form>
{% endblock %}

aspc/sagelist/templates/sagelist/booksale_table.html
{% load static %}

<table>
    <tr>
      <th class="title">Title</th>
      <th class="authors">Author(s)</th>
      <th class="isbn">ISBN</th>
      <th class="condition">Condition</th>
      <th class="course">Course</th>
      <th class="price">Price</th>
      <th class="copies">Copies</th>
      <th class="recoop">ReCoop</th>
    </tr>
  {% for book in listings %}
    <tr>
      <td class="title"><a href="{% url "sagelist_detail" pk=book.id %}">{{ book.title }}</a>{% if book.edition %} [{{ book.edition }} ed.]{% endif %}</td>
      <td class="authors">{{ book.authors }}</td>
      <td class="isbn">{{ book.isbn }}</td>
      <td class="condition">{{ book.get_condition_display }}</td>
      <td class="course">{{ book.course.code }}</td>
      <td class="price">${{ book.price }}{% if book.amazon_price %}<del>${{ book.amazon_price|floatformat:2  }}</del> {% endif %}</td>
      <td class="copies">{{ book.copies }}</td>
      <td class="recoop">{% if book.is_recoop %} <img src="{% static "images/recoop_listing_icon.png" %}" /> {% endif %}</td>
    </tr>
  {% endfor %}
  </table>